SECRETS_CIM_PROJECT_NAME = "cloud-iac-main"
SECRETS_CIM_CONFIG = "prd"
SECRETS_CIM_SLACK_BOT_MAIN_TOKEN = "SLACK_BOT_MAIN_TOKEN"

SECRETS_DS_PROJECT_NAME = "database-secrets"
SECRETS_DS_CONFIG = "prd"

FILE_PATH_CERT_CA = "/tmp/ca.pem"
FILE_PATH_CERT_MONGOD = "/tmp/mongod.pem"
